services:

  frontend:
    build:
      context: ./client
    container_name: toDoFrontend
    ports:
      - 8000:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    container_name: toDoBackend
    ports:
      - 5000:5000
    env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      
