
services:
  frontend:
    build:
      context: ./client
    container_name: toDoFrontend
    ports:
      - "8000:8000"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    container_name: toDoBackend
    ports:
      - "5000:5000"
    environment:
    - MONGODB_URI=${MONGODB_URI??mongodb+srv://amith:Hello%40mith18@mongodb.tyrxhwb.mongodb.net/To-Do}
