services:

  frontend:
    build:
      context: ./client
    container_name: toDoFrontend
    ports:
      - 8000:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    container_name: toDoBackend
    ports:
      - 5000:5000
    environment:
      - MONGODB_URI
    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://localhost:5000/health', res => process.exit(res.statusCode === 200 ? 0 : 1))\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

      
