
services:
  frontend:
    build:
      context: ./client
    container_name: toDoFrontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
    command: >
      sh -c "echo 'Waiting for backend to be ready...';
             until curl -s http://backend:5000/health; do
               sleep 2;
             done;
             echo 'Backend is ready! Starting frontend...';
             npm run dev"

  backend:
    build:
      context: ./server
    container_name: toDoBackend
    ports:
      - "5000:5000"

    # Local .env for fallback
    env_file:
      - ./server/.env

    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('http').get('http://localhost:5000/health', res => process.exit(res.statusCode === 200 ? 0 : 1))\""]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
