name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - test

jobs:
  build-and-test:
    if: github.event_name == 'pull_request' && github.base_ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and start services with Docker Compose
        run: docker compose -f compose.yaml up --build -d
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Wait for backend to be ready
        run: sleep 10

      - name: Run Jest tests inside backend container
        run: docker exec toDoBackend npm test

      - name: Stop and remove containers
        if: always()
        run: docker compose -f compose.yaml down

  # 2. For test branch → build, test, push to GHCR
  build-test-publish:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and start services with Docker Compose
        run: docker compose -f compose.yaml up --build -d
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Wait for backend to be ready
        run: sleep 10

      - name: Run Jest tests inside backend container
        run: docker exec toDoBackend npm test

      - name: Stop and remove containers
        if: always()
        run: docker compose -f compose.yaml down

      - name: Build and push Docker image to GHCR
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/todo-app-backend:${{ github.run_number }} ./server
          docker push ghcr.io/${{ github.repository_owner }}/todo-app-backend:${{ github.run_number }}

