name: CI/CD Pipeline

permissions:
  packages: write
  contents: read

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - test

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Create .env file for backend
        run: |
          mkdir -p server
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > server/.env
          echo "NODE_ENV=test" >> server/.env

      - name: Build and start services with Docker Compose
        run: docker compose -f compose.yaml up --build -d
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Wait for backend to be ready
        run: sleep 10

      - name: Run Jest tests inside backend container
        run: docker exec toDoBackend npm test

      - name: Stop and remove containers
        if: always()
        run: docker compose -f compose.yaml down

  test-and-publish:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/todo-app-backend:${{ github.run_number }} ./server
          docker push ghcr.io/${{ github.repository_owner }}/todo-app-backend:${{ github.run_number }}
          
